CXX = g++
CFLAGS = -std=c++17 -I/usr/local/include -I/opt/homebrew/include -I/Users/emirhurturk/VulkanSDK/1.4.313.0/macOS/include
LDFLAGS = -L/opt/homebrew/lib/ -lglfw -lvulkan -lpthread -lvulkan.1 -L/Users/emirhurturk/VulkanSDK/1.4.313.0/macOS/lib/ -Wl,-rpath,/Users/emirhurturk/VulkanSDK/1.4.313.0/macOS/lib/
TARGET = VulkanTest
SRC = main.cpp

$(TARGET): $(SRC)
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)

.PHONY: clean
clean:
	rm -f $(TARGET)
